### PR TITLE
Interaction with os

### PR DESCRIPTION
**Pull request by rakeshsagalagatte**
Hey !
This pull request will successfully launch the chrome in different operating systems like `linux` , `mac`  and   `windows`.

### CODE REVIEW

**Comment by Aswin-Poovadan** [comment]
Hey Rakesh,
Thanks for the contribution,kindly please check the indentation at line 19 ,found an error there and also you have misspelled the word **satisfied**.

**Comment by rakeshsagalagatte** [comment]
Hello @Aswin-Poovadan , Thank you for your suggestion , 
And  It's cleared now , is that 🆗 .
Thank you.

**Comment by Aswin-Poovadan** [comment]
Thanks @rakeshsagalagatte for your contribution and fast response.
Your PR is merged now

**Comment by rakeshsagalagatte** [comment]
Thanks Aswin 😃

**Pull request merged**
